import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import CartContextProvider from "@/context/CartContext";
import WishlistContextProvider from "@/context/WishlistContext";
import AddressContextProvider from "@/context/AddressContext";
import { Toaster } from "react-hot-toast";
import MainSessionProvider from "@/components/layout/MainSessionProvider/SessionProvider";
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CornerStone: Shop Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <MainSessionProvider>
          <WishlistContextProvider>
            <AddressContextProvider>
              <CartContextProvider>
                <Toaster />
                <Navbar />
                {children}
                <Footer />
              </CartContextProvider>
            </AddressContextProvider>
          </WishlistContextProvider>
        </MainSessionProvider>
      </body>
    </html>
  );
}
